[2024-02-14T10:36:12.847+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: python_xcom_dag_v1.greet scheduled__2024-02-05T00:00:00+00:00 [queued]>
[2024-02-14T10:36:12.851+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: python_xcom_dag_v1.greet scheduled__2024-02-05T00:00:00+00:00 [queued]>
[2024-02-14T10:36:12.852+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 6
[2024-02-14T10:36:12.888+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): greet> on 2024-02-05 00:00:00+00:00
[2024-02-14T10:36:12.893+0000] {standard_task_runner.py:60} INFO - Started process 52776 to run task
[2024-02-14T10:36:12.898+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'python_xcom_dag_v1', 'greet', 'scheduled__2024-02-05T00:00:00+00:00', '--job-id', '199', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_xcoms.py', '--cfg-path', '/tmp/tmplmttm7iv']
[2024-02-14T10:36:12.899+0000] {standard_task_runner.py:88} INFO - Job 199: Subtask greet
[2024-02-14T10:36:12.964+0000] {task_command.py:423} INFO - Running <TaskInstance: python_xcom_dag_v1.greet scheduled__2024-02-05T00:00:00+00:00 [running]> on host codespaces-57ffd0
[2024-02-14T10:36:13.076+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='raghu' AIRFLOW_CTX_DAG_ID='python_xcom_dag_v1' AIRFLOW_CTX_TASK_ID='greet' AIRFLOW_CTX_EXECUTION_DATE='2024-02-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-05T00:00:00+00:00'
[2024-02-14T10:36:13.077+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/codespace/.local/share/virtualenvs/airflow_sandbox-vp-HKq_L/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/codespace/.local/share/virtualenvs/airflow_sandbox-vp-HKq_L/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/codespace/.local/share/virtualenvs/airflow_sandbox-vp-HKq_L/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/workspaces/airflow_sandbox/airflow/dags/dag_with_xcoms.py", line 7, in greet
    name = ti.xcom_pull(task_id = "get_name", key = "name")
  File "/home/codespace/.local/share/virtualenvs/airflow_sandbox-vp-HKq_L/lib/python3.10/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
TypeError: TaskInstance.xcom_pull() got an unexpected keyword argument 'task_id'
[2024-02-14T10:36:13.080+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=python_xcom_dag_v1, task_id=greet, execution_date=20240205T000000, start_date=20240214T103612, end_date=20240214T103613
[2024-02-14T10:36:13.113+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 199 for task greet (TaskInstance.xcom_pull() got an unexpected keyword argument 'task_id'; 52776)
[2024-02-14T10:36:13.147+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-14T10:36:13.157+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-02-14T10:40:14.818+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: python_xcom_dag_v1.greet scheduled__2024-02-05T00:00:00+00:00 [queued]>
[2024-02-14T10:40:14.824+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: python_xcom_dag_v1.greet scheduled__2024-02-05T00:00:00+00:00 [queued]>
[2024-02-14T10:40:14.824+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 6
[2024-02-14T10:40:14.860+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): greet> on 2024-02-05 00:00:00+00:00
[2024-02-14T10:40:14.864+0000] {standard_task_runner.py:60} INFO - Started process 56549 to run task
[2024-02-14T10:40:14.867+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'python_xcom_dag_v1', 'greet', 'scheduled__2024-02-05T00:00:00+00:00', '--job-id', '197', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_xcoms.py', '--cfg-path', '/tmp/tmpg34b4spx']
[2024-02-14T10:40:14.868+0000] {standard_task_runner.py:88} INFO - Job 197: Subtask greet
[2024-02-14T10:40:14.930+0000] {task_command.py:423} INFO - Running <TaskInstance: python_xcom_dag_v1.greet scheduled__2024-02-05T00:00:00+00:00 [running]> on host codespaces-57ffd0
[2024-02-14T10:40:15.028+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='raghu' AIRFLOW_CTX_DAG_ID='python_xcom_dag_v1' AIRFLOW_CTX_TASK_ID='greet' AIRFLOW_CTX_EXECUTION_DATE='2024-02-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-05T00:00:00+00:00'
[2024-02-14T10:40:15.034+0000] {logging_mixin.py:188} INFO - My name is Raghu and I am 22 years old
[2024-02-14T10:40:15.034+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-14T10:40:15.037+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=python_xcom_dag_v1, task_id=greet, execution_date=20240205T000000, start_date=20240214T104014, end_date=20240214T104015
[2024-02-14T10:40:15.079+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-14T10:40:15.089+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
