[2024-02-14T20:21:05.307+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator.insert_data_into_pg_db manual__2024-02-14T20:20:51.498130+00:00 [queued]>
[2024-02-14T20:21:05.316+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator.insert_data_into_pg_db manual__2024-02-14T20:20:51.498130+00:00 [queued]>
[2024-02-14T20:21:05.316+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 6
[2024-02-14T20:21:05.365+0000] {taskinstance.py:2192} INFO - Executing <Task(PostgresOperator): insert_data_into_pg_db> on 2024-02-14 20:20:51.498130+00:00
[2024-02-14T20:21:05.370+0000] {standard_task_runner.py:60} INFO - Started process 68967 to run task
[2024-02-14T20:21:05.373+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_postgres_operator', 'insert_data_into_pg_db', 'manual__2024-02-14T20:20:51.498130+00:00', '--job-id', '323', '--raw', '--subdir', 'DAGS_FOLDER/pg_op_dag.py', '--cfg-path', '/tmp/tmpk9e_4sqb']
[2024-02-14T20:21:05.374+0000] {standard_task_runner.py:88} INFO - Job 323: Subtask insert_data_into_pg_db
[2024-02-14T20:21:05.428+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_with_postgres_operator.insert_data_into_pg_db manual__2024-02-14T20:20:51.498130+00:00 [running]> on host codespaces-57ffd0
[2024-02-14T20:21:05.526+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='raghu' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator' AIRFLOW_CTX_TASK_ID='insert_data_into_pg_db' AIRFLOW_CTX_EXECUTION_DATE='2024-02-14T20:20:51.498130+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-14T20:20:51.498130+00:00'
[2024-02-14T20:21:05.526+0000] {sql.py:276} INFO - Executing: insert into dag_runs values('Raghu', 25);
[2024-02-14T20:21:05.530+0000] {base.py:83} INFO - Using connection ID 'postgres_db_connection' for task execution.
[2024-02-14T20:21:05.549+0000] {base.py:83} INFO - Using connection ID 'postgres_db_connection' for task execution.
[2024-02-14T20:21:06.764+0000] {sql.py:450} INFO - Running statement: insert into dag_runs values('Raghu', 25);, parameters: None
[2024-02-14T20:21:07.231+0000] {sql.py:459} INFO - Rows affected: 1
[2024-02-14T20:21:07.467+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator, task_id=insert_data_into_pg_db, execution_date=20240214T202051, start_date=20240214T202105, end_date=20240214T202107
[2024-02-14T20:21:07.515+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-14T20:21:07.524+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
